// @generated by lenso-contract-codegen; do not edit.
use std::{fmt, rc::Rc};
use futures::future::LocalBoxFuture;
use lenso_kernel::{InvocationContext, NativeRequestEndpoint, NativeRequestFuture, NativeRequestHandle, NativeStream, NativeStreamEndpoint, NativeStreamHandle, NativeStreamSession, PluginDependencies, RequestCapability, RuntimeFailure, StreamCapability, StreamEvent};

use lenso_plugin_authoring::{BoundCapabilityClient, CapabilityClient, CapabilityClientMany};
pub const CAPABILITY_ID: &str = "lenso.content-vault@1";
pub const DESCRIPTOR_VERSION: &str = "1.0.0";
pub const PORTABLE: bool = true;
pub const CROSS_LANE_TRANSFER: bool = false;
pub const CONTENT_VAULT_CAPABILITY_ID: &str = CAPABILITY_ID;
pub const CONTENT_VAULT_DESCRIPTOR_VERSION: &str = DESCRIPTOR_VERSION;

#[doc(hidden)]
#[macro_export]
macro_rules! __lenso_provided_content_vault { () => { "{\"capability_id\":\"lenso.content-vault@1\",\"descriptor_version\":\"1.0.0\",\"operations\":[\"claim\",\"describe\",\"download\",\"release_claim\",\"reserve\",\"sweep\",\"upload\"],\"operation_kinds\":{\"download\":\"stream\",\"upload\":\"stream\"},\"default_admission\":{\"queue_capacity\":0,\"max_concurrency\":1},\"operation_admissions\":{},\"event_admission\":null,\"cross_lane_transfer\":false}" }; }

#[doc(hidden)]
#[macro_export]
macro_rules! __lenso_required_content_vault_client { () => { "{\"capability_id\":\"lenso.content-vault@1\",\"descriptor_version\":\"1.0.0\",\"cardinality\":\"one\"}" }; }

#[doc(hidden)]
#[macro_export]
macro_rules! __lenso_required_many_content_vault_client { () => { "{\"capability_id\":\"lenso.content-vault@1\",\"descriptor_version\":\"1.0.0\",\"cardinality\":\"many\"}" }; }

pub const CLAIM_OPERATION: &str = "claim";
pub const DESCRIBE_OPERATION: &str = "describe";
pub const DOWNLOAD_OPERATION: &str = "download";
pub const RELEASE_CLAIM_OPERATION: &str = "release_claim";
pub const RESERVE_OPERATION: &str = "reserve";
pub const SWEEP_OPERATION: &str = "sweep";
pub const UPLOAD_OPERATION: &str = "upload";

pub use lenso_contract_runtime::{OptionalValue, Timestamp, UnknownDomainError};
use lenso_contract_runtime::{decode_portable_json, encode_portable_json};

#[derive(Clone, Debug, PartialEq, serde::Serialize, serde::Deserialize)]
pub struct ClaimRequest {
    #[serde(rename = "content_id")]
    #[serde(deserialize_with = "lenso_contract_runtime::serde::deserialize_required")]
    pub content_id: String,
    #[serde(rename = "grant")]
    #[serde(deserialize_with = "lenso_contract_runtime::serde::deserialize_required")]
    pub grant: OwnerGrant,
    #[serde(rename = "role")]
    #[serde(deserialize_with = "lenso_contract_runtime::serde::deserialize_required")]
    pub role: String,
    #[serde(rename = "target")]
    #[serde(deserialize_with = "lenso_contract_runtime::serde::deserialize_required")]
    pub target: Owner,
}

#[derive(Clone, Debug, PartialEq, serde::Serialize, serde::Deserialize)]
pub struct OwnerGrant {
    #[serde(rename = "actor_id")]
    #[serde(deserialize_with = "lenso_contract_runtime::serde::deserialize_required")]
    pub actor_id: String,
    #[serde(rename = "correlation_id")]
    #[serde(deserialize_with = "lenso_contract_runtime::serde::deserialize_required")]
    pub correlation_id: String,
    #[serde(rename = "owner")]
    #[serde(deserialize_with = "lenso_contract_runtime::serde::deserialize_required")]
    pub owner: Owner,
    #[serde(rename = "tenant_id")]
    #[serde(deserialize_with = "lenso_contract_runtime::serde::deserialize_required")]
    pub tenant_id: String,
}

#[derive(Clone, Debug, PartialEq, serde::Serialize, serde::Deserialize)]
pub struct Owner {
    #[serde(rename = "plugin_instance")]
    #[serde(deserialize_with = "lenso_contract_runtime::serde::deserialize_required")]
    pub plugin_instance: String,
    #[serde(rename = "resource_id")]
    #[serde(deserialize_with = "lenso_contract_runtime::serde::deserialize_required")]
    pub resource_id: String,
    #[serde(rename = "resource_type")]
    #[serde(deserialize_with = "lenso_contract_runtime::serde::deserialize_required")]
    pub resource_type: String,
    #[serde(rename = "revision_id")]
    #[serde(default)]
    #[serde(skip_serializing_if = "Option::is_none")]
    #[serde(deserialize_with = "lenso_contract_runtime::serde::deserialize_optional_value")]
    pub revision_id: OptionalValue<String>,
}

#[derive(Clone, Debug, PartialEq, serde::Serialize, serde::Deserialize)]
pub struct ClaimResponse {
    #[serde(rename = "active")]
    #[serde(deserialize_with = "lenso_contract_runtime::serde::deserialize_required")]
    pub active: bool,
}

#[derive(Clone, Debug, PartialEq)]
pub enum ClaimError {
    Conflict,
    IntegrityMismatch,
    IntegrityMissing,
    InvalidInput,
    NotFound,
    Unauthorized,
    UploadExpired,
    UploadInterrupted,
    UploadMissing,
    UploadRejected,
    Unknown(UnknownDomainError),
}

#[derive(Clone, Debug, PartialEq, serde::Serialize, serde::Deserialize)]
pub struct DescribeRequest {
    #[serde(rename = "content_id")]
    #[serde(deserialize_with = "lenso_contract_runtime::serde::deserialize_required")]
    pub content_id: String,
    #[serde(rename = "grant")]
    #[serde(deserialize_with = "lenso_contract_runtime::serde::deserialize_required")]
    pub grant: OwnerGrant,
}

#[derive(Clone, Debug, PartialEq, serde::Serialize, serde::Deserialize)]
pub struct DescribeResponse {
    #[serde(rename = "content")]
    #[serde(deserialize_with = "lenso_contract_runtime::serde::deserialize_required")]
    pub content: ContentDescriptor,
}

#[derive(Clone, Debug, PartialEq, serde::Serialize, serde::Deserialize)]
pub struct ContentDescriptor {
    #[serde(rename = "content_id")]
    #[serde(deserialize_with = "lenso_contract_runtime::serde::deserialize_required")]
    pub content_id: String,
    #[serde(rename = "created_at")]
    #[serde(deserialize_with = "lenso_contract_runtime::serde::deserialize_required")]
    pub created_at: Timestamp,
    #[serde(rename = "media_type")]
    #[serde(deserialize_with = "lenso_contract_runtime::serde::deserialize_required")]
    pub media_type: String,
    #[serde(rename = "sha256")]
    #[serde(deserialize_with = "lenso_contract_runtime::serde::deserialize_required")]
    pub sha256: String,
    #[serde(rename = "size_bytes")]
    #[serde(deserialize_with = "lenso_contract_runtime::serde::deserialize_required")]
    pub size_bytes: i64,
}

#[derive(Clone, Debug, PartialEq)]
pub enum DescribeError {
    Conflict,
    IntegrityMismatch,
    IntegrityMissing,
    InvalidInput,
    NotFound,
    Unauthorized,
    UploadExpired,
    UploadInterrupted,
    UploadMissing,
    UploadRejected,
    Unknown(UnknownDomainError),
}

#[derive(Clone, Debug, PartialEq, serde::Serialize, serde::Deserialize)]
pub struct DownloadRequest {
    #[serde(rename = "content_id")]
    #[serde(deserialize_with = "lenso_contract_runtime::serde::deserialize_required")]
    pub content_id: String,
    #[serde(rename = "grant")]
    #[serde(deserialize_with = "lenso_contract_runtime::serde::deserialize_required")]
    pub grant: OwnerGrant,
}

#[derive(Clone, PartialEq, serde::Serialize, serde::Deserialize)]
pub struct DownloadFrame {
    #[serde(rename = "bytes_base64")]
    #[serde(default)]
    #[serde(skip_serializing_if = "Option::is_none")]
    #[serde(deserialize_with = "lenso_contract_runtime::serde::deserialize_optional_value")]
    pub bytes_base64: OptionalValue<String>,
    #[serde(rename = "content")]
    #[serde(default)]
    #[serde(skip_serializing_if = "Option::is_none")]
    #[serde(deserialize_with = "lenso_contract_runtime::serde::deserialize_optional_value")]
    pub content: OptionalValue<ContentDescriptor>,
    #[serde(rename = "kind")]
    #[serde(deserialize_with = "lenso_contract_runtime::serde::deserialize_required")]
    pub kind: DownloadFrameKind,
    #[serde(rename = "offset")]
    #[serde(deserialize_with = "lenso_contract_runtime::serde::deserialize_required")]
    pub offset: Option<i64>,
}

impl fmt::Debug for DownloadFrame {
    fn fmt(&self, formatter: &mut fmt::Formatter<'_>) -> fmt::Result {
        formatter
            .debug_struct("DownloadFrame")
            .field("bytes_base64", &"<redacted>")
            .field("content", &self.content)
            .field("kind", &self.kind)
            .field("offset", &self.offset)
            .finish()
    }
}

#[derive(Clone, Debug, PartialEq, serde::Serialize, serde::Deserialize)]
pub enum DownloadFrameKind {
    #[serde(rename = "descriptor")]
    Descriptor,
    #[serde(rename = "chunk")]
    Chunk,
}

#[derive(Clone, Debug, PartialEq)]
pub enum DownloadError {
    Conflict,
    IntegrityMismatch,
    IntegrityMissing,
    InvalidInput,
    NotFound,
    Unauthorized,
    UploadExpired,
    UploadInterrupted,
    UploadMissing,
    UploadRejected,
    Unknown(UnknownDomainError),
}

#[derive(Clone, Debug, PartialEq, serde::Serialize, serde::Deserialize)]
pub struct ReleaseClaimRequest {
    #[serde(rename = "content_id")]
    #[serde(deserialize_with = "lenso_contract_runtime::serde::deserialize_required")]
    pub content_id: String,
    #[serde(rename = "grant")]
    #[serde(deserialize_with = "lenso_contract_runtime::serde::deserialize_required")]
    pub grant: OwnerGrant,
    #[serde(rename = "role")]
    #[serde(deserialize_with = "lenso_contract_runtime::serde::deserialize_required")]
    pub role: String,
    #[serde(rename = "target")]
    #[serde(deserialize_with = "lenso_contract_runtime::serde::deserialize_required")]
    pub target: Owner,
}

#[derive(Clone, Debug, PartialEq, serde::Serialize, serde::Deserialize)]
pub struct ReleaseClaimResponse {
    #[serde(rename = "released")]
    #[serde(deserialize_with = "lenso_contract_runtime::serde::deserialize_required")]
    pub released: bool,
}

#[derive(Clone, Debug, PartialEq)]
pub enum ReleaseClaimError {
    Conflict,
    IntegrityMismatch,
    IntegrityMissing,
    InvalidInput,
    NotFound,
    Unauthorized,
    UploadExpired,
    UploadInterrupted,
    UploadMissing,
    UploadRejected,
    Unknown(UnknownDomainError),
}

#[derive(Clone, Debug, PartialEq, serde::Serialize, serde::Deserialize)]
pub struct ReserveRequest {
    #[serde(rename = "expected_sha256")]
    #[serde(deserialize_with = "lenso_contract_runtime::serde::deserialize_required")]
    pub expected_sha256: String,
    #[serde(rename = "expected_size_bytes")]
    #[serde(deserialize_with = "lenso_contract_runtime::serde::deserialize_required")]
    pub expected_size_bytes: i64,
    #[serde(rename = "grant")]
    #[serde(deserialize_with = "lenso_contract_runtime::serde::deserialize_required")]
    pub grant: OwnerGrant,
    #[serde(rename = "idempotency_key")]
    #[serde(deserialize_with = "lenso_contract_runtime::serde::deserialize_required")]
    pub idempotency_key: String,
    #[serde(rename = "media_type")]
    #[serde(deserialize_with = "lenso_contract_runtime::serde::deserialize_required")]
    pub media_type: String,
    #[serde(rename = "ttl_seconds")]
    #[serde(deserialize_with = "lenso_contract_runtime::serde::deserialize_required")]
    pub ttl_seconds: i64,
}

#[derive(Clone, Debug, PartialEq, serde::Serialize, serde::Deserialize)]
pub struct ReserveResponse {
    #[serde(rename = "expected_sha256")]
    #[serde(deserialize_with = "lenso_contract_runtime::serde::deserialize_required")]
    pub expected_sha256: String,
    #[serde(rename = "expected_size_bytes")]
    #[serde(deserialize_with = "lenso_contract_runtime::serde::deserialize_required")]
    pub expected_size_bytes: i64,
    #[serde(rename = "expires_at")]
    #[serde(deserialize_with = "lenso_contract_runtime::serde::deserialize_required")]
    pub expires_at: Timestamp,
    #[serde(rename = "media_type")]
    #[serde(deserialize_with = "lenso_contract_runtime::serde::deserialize_required")]
    pub media_type: String,
    #[serde(rename = "next_offset")]
    #[serde(deserialize_with = "lenso_contract_runtime::serde::deserialize_required")]
    pub next_offset: i64,
    #[serde(rename = "session_id")]
    #[serde(deserialize_with = "lenso_contract_runtime::serde::deserialize_required")]
    pub session_id: String,
    #[serde(rename = "state")]
    #[serde(deserialize_with = "lenso_contract_runtime::serde::deserialize_required")]
    pub state: UploadState,
}

#[derive(Clone, Debug, PartialEq, serde::Serialize, serde::Deserialize)]
pub enum UploadState {
    #[serde(rename = "reserved")]
    Reserved,
    #[serde(rename = "staging")]
    Staging,
    #[serde(rename = "committed")]
    Committed,
    #[serde(rename = "rejected")]
    Rejected,
    #[serde(rename = "expired")]
    Expired,
}

#[derive(Clone, Debug, PartialEq)]
pub enum ReserveError {
    Conflict,
    IntegrityMismatch,
    IntegrityMissing,
    InvalidInput,
    NotFound,
    Unauthorized,
    UploadExpired,
    UploadInterrupted,
    UploadMissing,
    UploadRejected,
    Unknown(UnknownDomainError),
}

#[derive(Clone, Debug, PartialEq, serde::Serialize, serde::Deserialize)]
pub struct SweepRequest {

}

#[derive(Clone, Debug, PartialEq, serde::Serialize, serde::Deserialize)]
pub struct SweepResponse {
    #[serde(rename = "cleaned_objects")]
    #[serde(deserialize_with = "lenso_contract_runtime::serde::deserialize_required")]
    pub cleaned_objects: i64,
    #[serde(rename = "expired_sessions")]
    #[serde(deserialize_with = "lenso_contract_runtime::serde::deserialize_required")]
    pub expired_sessions: i64,
    #[serde(rename = "failed_objects")]
    #[serde(deserialize_with = "lenso_contract_runtime::serde::deserialize_required")]
    pub failed_objects: i64,
}

#[derive(Clone, Debug, PartialEq)]
pub enum SweepError {
    Conflict,
    IntegrityMismatch,
    IntegrityMissing,
    InvalidInput,
    NotFound,
    Unauthorized,
    UploadExpired,
    UploadInterrupted,
    UploadMissing,
    UploadRejected,
    Unknown(UnknownDomainError),
}

#[derive(Clone, Debug, PartialEq, serde::Serialize, serde::Deserialize)]
pub struct UploadRequest {
    #[serde(rename = "grant")]
    #[serde(deserialize_with = "lenso_contract_runtime::serde::deserialize_required")]
    pub grant: OwnerGrant,
    #[serde(rename = "session_id")]
    #[serde(deserialize_with = "lenso_contract_runtime::serde::deserialize_required")]
    pub session_id: String,
}

#[derive(Clone, PartialEq, serde::Serialize, serde::Deserialize)]
pub struct UploadFrame {
    #[serde(rename = "bytes_base64")]
    #[serde(default)]
    #[serde(skip_serializing_if = "Option::is_none")]
    #[serde(deserialize_with = "lenso_contract_runtime::serde::deserialize_optional_value")]
    pub bytes_base64: OptionalValue<String>,
    #[serde(rename = "content")]
    #[serde(default)]
    #[serde(skip_serializing_if = "Option::is_none")]
    #[serde(deserialize_with = "lenso_contract_runtime::serde::deserialize_optional_value")]
    pub content: OptionalValue<ContentDescriptor>,
    #[serde(rename = "kind")]
    #[serde(deserialize_with = "lenso_contract_runtime::serde::deserialize_required")]
    pub kind: UploadFrameKind,
    #[serde(rename = "offset")]
    #[serde(deserialize_with = "lenso_contract_runtime::serde::deserialize_required")]
    pub offset: Option<i64>,
}

impl fmt::Debug for UploadFrame {
    fn fmt(&self, formatter: &mut fmt::Formatter<'_>) -> fmt::Result {
        formatter
            .debug_struct("UploadFrame")
            .field("bytes_base64", &"<redacted>")
            .field("content", &self.content)
            .field("kind", &self.kind)
            .field("offset", &self.offset)
            .finish()
    }
}

#[derive(Clone, Debug, PartialEq, serde::Serialize, serde::Deserialize)]
pub enum UploadFrameKind {
    #[serde(rename = "chunk")]
    Chunk,
    #[serde(rename = "committed")]
    Committed,
}

#[derive(Clone, Debug, PartialEq)]
pub enum UploadError {
    Conflict,
    IntegrityMismatch,
    IntegrityMissing,
    InvalidInput,
    NotFound,
    Unauthorized,
    UploadExpired,
    UploadInterrupted,
    UploadMissing,
    UploadRejected,
    Unknown(UnknownDomainError),
}

#[derive(Debug)]
pub struct ContentVaultClaim;
impl RequestCapability for ContentVaultClaim {
    type Request = ClaimRequest;
    type Response = ClaimResponse;
    type DomainError = ClaimError;
    const ID: &'static str = CAPABILITY_ID;
    const DESCRIPTOR_VERSION: &'static str = DESCRIPTOR_VERSION;

    fn invoke_native(endpoint: &dyn NativeRequestEndpoint, operation: &str, request: Self::Request, context: InvocationContext) -> NativeRequestFuture<Self> {
        if operation != CLAIM_OPERATION {
            return lenso_kernel::invoke_typed_or_erased_native_request::<Self>(endpoint, operation, request, context);
        }
        let Some(typed_endpoint) = endpoint
            .typed_endpoint()
            .and_then(|endpoint| endpoint.downcast_ref::<ContentVaultRequestEndpoint>())
        else {
            return lenso_kernel::invoke_typed_or_erased_native_request::<Self>(endpoint, operation, request, context);
        };
        Rc::clone(&typed_endpoint.provider).claim(context, request)
    }
}

#[derive(Debug)]
pub struct ContentVaultDescribe;
impl RequestCapability for ContentVaultDescribe {
    type Request = DescribeRequest;
    type Response = DescribeResponse;
    type DomainError = DescribeError;
    const ID: &'static str = CAPABILITY_ID;
    const DESCRIPTOR_VERSION: &'static str = DESCRIPTOR_VERSION;

    fn invoke_native(endpoint: &dyn NativeRequestEndpoint, operation: &str, request: Self::Request, context: InvocationContext) -> NativeRequestFuture<Self> {
        if operation != DESCRIBE_OPERATION {
            return lenso_kernel::invoke_typed_or_erased_native_request::<Self>(endpoint, operation, request, context);
        }
        let Some(typed_endpoint) = endpoint
            .typed_endpoint()
            .and_then(|endpoint| endpoint.downcast_ref::<ContentVaultRequestEndpoint>())
        else {
            return lenso_kernel::invoke_typed_or_erased_native_request::<Self>(endpoint, operation, request, context);
        };
        Rc::clone(&typed_endpoint.provider).describe(context, request)
    }
}

#[derive(Debug)]
pub struct ContentVaultDownload;
pub type ContentVaultDownloadEvent = StreamEvent<DownloadFrame, DownloadError>;
impl StreamCapability for ContentVaultDownload {
    type OpenRequest = DownloadRequest;
    type Message = DownloadFrame;
    type DomainError = DownloadError;
    const ID: &'static str = CAPABILITY_ID;
    const DESCRIPTOR_VERSION: &'static str = DESCRIPTOR_VERSION;
}

#[derive(Debug)]
pub struct ContentVaultReleaseClaim;
impl RequestCapability for ContentVaultReleaseClaim {
    type Request = ReleaseClaimRequest;
    type Response = ReleaseClaimResponse;
    type DomainError = ReleaseClaimError;
    const ID: &'static str = CAPABILITY_ID;
    const DESCRIPTOR_VERSION: &'static str = DESCRIPTOR_VERSION;

    fn invoke_native(endpoint: &dyn NativeRequestEndpoint, operation: &str, request: Self::Request, context: InvocationContext) -> NativeRequestFuture<Self> {
        if operation != RELEASE_CLAIM_OPERATION {
            return lenso_kernel::invoke_typed_or_erased_native_request::<Self>(endpoint, operation, request, context);
        }
        let Some(typed_endpoint) = endpoint
            .typed_endpoint()
            .and_then(|endpoint| endpoint.downcast_ref::<ContentVaultRequestEndpoint>())
        else {
            return lenso_kernel::invoke_typed_or_erased_native_request::<Self>(endpoint, operation, request, context);
        };
        Rc::clone(&typed_endpoint.provider).release_claim(context, request)
    }
}

#[derive(Debug)]
pub struct ContentVaultReserve;
impl RequestCapability for ContentVaultReserve {
    type Request = ReserveRequest;
    type Response = ReserveResponse;
    type DomainError = ReserveError;
    const ID: &'static str = CAPABILITY_ID;
    const DESCRIPTOR_VERSION: &'static str = DESCRIPTOR_VERSION;

    fn invoke_native(endpoint: &dyn NativeRequestEndpoint, operation: &str, request: Self::Request, context: InvocationContext) -> NativeRequestFuture<Self> {
        if operation != RESERVE_OPERATION {
            return lenso_kernel::invoke_typed_or_erased_native_request::<Self>(endpoint, operation, request, context);
        }
        let Some(typed_endpoint) = endpoint
            .typed_endpoint()
            .and_then(|endpoint| endpoint.downcast_ref::<ContentVaultRequestEndpoint>())
        else {
            return lenso_kernel::invoke_typed_or_erased_native_request::<Self>(endpoint, operation, request, context);
        };
        Rc::clone(&typed_endpoint.provider).reserve(context, request)
    }
}

#[derive(Debug)]
pub struct ContentVaultSweep;
impl RequestCapability for ContentVaultSweep {
    type Request = SweepRequest;
    type Response = SweepResponse;
    type DomainError = SweepError;
    const ID: &'static str = CAPABILITY_ID;
    const DESCRIPTOR_VERSION: &'static str = DESCRIPTOR_VERSION;

    fn invoke_native(endpoint: &dyn NativeRequestEndpoint, operation: &str, request: Self::Request, context: InvocationContext) -> NativeRequestFuture<Self> {
        if operation != SWEEP_OPERATION {
            return lenso_kernel::invoke_typed_or_erased_native_request::<Self>(endpoint, operation, request, context);
        }
        let Some(typed_endpoint) = endpoint
            .typed_endpoint()
            .and_then(|endpoint| endpoint.downcast_ref::<ContentVaultRequestEndpoint>())
        else {
            return lenso_kernel::invoke_typed_or_erased_native_request::<Self>(endpoint, operation, request, context);
        };
        Rc::clone(&typed_endpoint.provider).sweep(context, request)
    }
}

#[derive(Debug)]
pub struct ContentVaultUpload;
pub type ContentVaultUploadEvent = StreamEvent<UploadFrame, UploadError>;
impl StreamCapability for ContentVaultUpload {
    type OpenRequest = UploadRequest;
    type Message = UploadFrame;
    type DomainError = UploadError;
    const ID: &'static str = CAPABILITY_ID;
    const DESCRIPTOR_VERSION: &'static str = DESCRIPTOR_VERSION;
}

impl serde::Serialize for ClaimError {
    fn serialize<S>(&self, serializer: S) -> Result<S::Ok, S::Error>
    where
        S: serde::Serializer,
    {
        use serde::ser::SerializeMap;
        match self {
            Self::Conflict => serializer.serialize_str("conflict"),
            Self::IntegrityMismatch => serializer.serialize_str("integrity_mismatch"),
            Self::IntegrityMissing => serializer.serialize_str("integrity_missing"),
            Self::InvalidInput => serializer.serialize_str("invalid_input"),
            Self::NotFound => serializer.serialize_str("not_found"),
            Self::Unauthorized => serializer.serialize_str("unauthorized"),
            Self::UploadExpired => serializer.serialize_str("upload_expired"),
            Self::UploadInterrupted => serializer.serialize_str("upload_interrupted"),
            Self::UploadMissing => serializer.serialize_str("upload_missing"),
            Self::UploadRejected => serializer.serialize_str("upload_rejected"),
            Self::Unknown(value) => {
                let mut map = serializer.serialize_map(Some(1 + usize::from(value.payload.is_some()) + value.extra.len()))?;
                map.serialize_entry("code", &value.code)?;
                if let Some(payload) = &value.payload {
                    map.serialize_entry("payload", payload)?;
                }
                for (key, extra) in &value.extra {
                    map.serialize_entry(key, extra)?;
                }
                map.end()
            },
        }
    }
}

impl<'de> serde::Deserialize<'de> for ClaimError {
    fn deserialize<D>(deserializer: D) -> Result<Self, D::Error>
    where
        D: serde::Deserializer<'de>,
    {
        let value = <serde_json::Value as serde::Deserialize>::deserialize(deserializer)?;
        match value {
            serde_json::Value::String(code) => match code.as_str() {
                "conflict" => Ok(Self::Conflict),
                "integrity_mismatch" => Ok(Self::IntegrityMismatch),
                "integrity_missing" => Ok(Self::IntegrityMissing),
                "invalid_input" => Ok(Self::InvalidInput),
                "not_found" => Ok(Self::NotFound),
                "unauthorized" => Ok(Self::Unauthorized),
                "upload_expired" => Ok(Self::UploadExpired),
                "upload_interrupted" => Ok(Self::UploadInterrupted),
                "upload_missing" => Ok(Self::UploadMissing),
                "upload_rejected" => Ok(Self::UploadRejected),
                _ => Ok(Self::Unknown(UnknownDomainError { code, payload: None, extra: std::collections::BTreeMap::new() })),
            },
            serde_json::Value::Object(mut object) => {
                let Some(code) = object.remove("code").and_then(|value| value.as_str().map(ToOwned::to_owned)) else {
                    return Err(serde::de::Error::custom("Domain Error object is missing a string code"));
                };
                let payload = object.remove("payload");
                let extra = object.into_iter().collect::<std::collections::BTreeMap<_, _>>();
                Ok(Self::Unknown(UnknownDomainError { code, payload, extra }))
            }
            other => Err(serde::de::Error::custom(format!("Domain Error must be a string or object, got {other}"))),
        }
    }
}

impl serde::Serialize for DescribeError {
    fn serialize<S>(&self, serializer: S) -> Result<S::Ok, S::Error>
    where
        S: serde::Serializer,
    {
        use serde::ser::SerializeMap;
        match self {
            Self::Conflict => serializer.serialize_str("conflict"),
            Self::IntegrityMismatch => serializer.serialize_str("integrity_mismatch"),
            Self::IntegrityMissing => serializer.serialize_str("integrity_missing"),
            Self::InvalidInput => serializer.serialize_str("invalid_input"),
            Self::NotFound => serializer.serialize_str("not_found"),
            Self::Unauthorized => serializer.serialize_str("unauthorized"),
            Self::UploadExpired => serializer.serialize_str("upload_expired"),
            Self::UploadInterrupted => serializer.serialize_str("upload_interrupted"),
            Self::UploadMissing => serializer.serialize_str("upload_missing"),
            Self::UploadRejected => serializer.serialize_str("upload_rejected"),
            Self::Unknown(value) => {
                let mut map = serializer.serialize_map(Some(1 + usize::from(value.payload.is_some()) + value.extra.len()))?;
                map.serialize_entry("code", &value.code)?;
                if let Some(payload) = &value.payload {
                    map.serialize_entry("payload", payload)?;
                }
                for (key, extra) in &value.extra {
                    map.serialize_entry(key, extra)?;
                }
                map.end()
            },
        }
    }
}

impl<'de> serde::Deserialize<'de> for DescribeError {
    fn deserialize<D>(deserializer: D) -> Result<Self, D::Error>
    where
        D: serde::Deserializer<'de>,
    {
        let value = <serde_json::Value as serde::Deserialize>::deserialize(deserializer)?;
        match value {
            serde_json::Value::String(code) => match code.as_str() {
                "conflict" => Ok(Self::Conflict),
                "integrity_mismatch" => Ok(Self::IntegrityMismatch),
                "integrity_missing" => Ok(Self::IntegrityMissing),
                "invalid_input" => Ok(Self::InvalidInput),
                "not_found" => Ok(Self::NotFound),
                "unauthorized" => Ok(Self::Unauthorized),
                "upload_expired" => Ok(Self::UploadExpired),
                "upload_interrupted" => Ok(Self::UploadInterrupted),
                "upload_missing" => Ok(Self::UploadMissing),
                "upload_rejected" => Ok(Self::UploadRejected),
                _ => Ok(Self::Unknown(UnknownDomainError { code, payload: None, extra: std::collections::BTreeMap::new() })),
            },
            serde_json::Value::Object(mut object) => {
                let Some(code) = object.remove("code").and_then(|value| value.as_str().map(ToOwned::to_owned)) else {
                    return Err(serde::de::Error::custom("Domain Error object is missing a string code"));
                };
                let payload = object.remove("payload");
                let extra = object.into_iter().collect::<std::collections::BTreeMap<_, _>>();
                Ok(Self::Unknown(UnknownDomainError { code, payload, extra }))
            }
            other => Err(serde::de::Error::custom(format!("Domain Error must be a string or object, got {other}"))),
        }
    }
}

impl serde::Serialize for DownloadError {
    fn serialize<S>(&self, serializer: S) -> Result<S::Ok, S::Error>
    where
        S: serde::Serializer,
    {
        use serde::ser::SerializeMap;
        match self {
            Self::Conflict => serializer.serialize_str("conflict"),
            Self::IntegrityMismatch => serializer.serialize_str("integrity_mismatch"),
            Self::IntegrityMissing => serializer.serialize_str("integrity_missing"),
            Self::InvalidInput => serializer.serialize_str("invalid_input"),
            Self::NotFound => serializer.serialize_str("not_found"),
            Self::Unauthorized => serializer.serialize_str("unauthorized"),
            Self::UploadExpired => serializer.serialize_str("upload_expired"),
            Self::UploadInterrupted => serializer.serialize_str("upload_interrupted"),
            Self::UploadMissing => serializer.serialize_str("upload_missing"),
            Self::UploadRejected => serializer.serialize_str("upload_rejected"),
            Self::Unknown(value) => {
                let mut map = serializer.serialize_map(Some(1 + usize::from(value.payload.is_some()) + value.extra.len()))?;
                map.serialize_entry("code", &value.code)?;
                if let Some(payload) = &value.payload {
                    map.serialize_entry("payload", payload)?;
                }
                for (key, extra) in &value.extra {
                    map.serialize_entry(key, extra)?;
                }
                map.end()
            },
        }
    }
}

impl<'de> serde::Deserialize<'de> for DownloadError {
    fn deserialize<D>(deserializer: D) -> Result<Self, D::Error>
    where
        D: serde::Deserializer<'de>,
    {
        let value = <serde_json::Value as serde::Deserialize>::deserialize(deserializer)?;
        match value {
            serde_json::Value::String(code) => match code.as_str() {
                "conflict" => Ok(Self::Conflict),
                "integrity_mismatch" => Ok(Self::IntegrityMismatch),
                "integrity_missing" => Ok(Self::IntegrityMissing),
                "invalid_input" => Ok(Self::InvalidInput),
                "not_found" => Ok(Self::NotFound),
                "unauthorized" => Ok(Self::Unauthorized),
                "upload_expired" => Ok(Self::UploadExpired),
                "upload_interrupted" => Ok(Self::UploadInterrupted),
                "upload_missing" => Ok(Self::UploadMissing),
                "upload_rejected" => Ok(Self::UploadRejected),
                _ => Ok(Self::Unknown(UnknownDomainError { code, payload: None, extra: std::collections::BTreeMap::new() })),
            },
            serde_json::Value::Object(mut object) => {
                let Some(code) = object.remove("code").and_then(|value| value.as_str().map(ToOwned::to_owned)) else {
                    return Err(serde::de::Error::custom("Domain Error object is missing a string code"));
                };
                let payload = object.remove("payload");
                let extra = object.into_iter().collect::<std::collections::BTreeMap<_, _>>();
                Ok(Self::Unknown(UnknownDomainError { code, payload, extra }))
            }
            other => Err(serde::de::Error::custom(format!("Domain Error must be a string or object, got {other}"))),
        }
    }
}

impl serde::Serialize for ReleaseClaimError {
    fn serialize<S>(&self, serializer: S) -> Result<S::Ok, S::Error>
    where
        S: serde::Serializer,
    {
        use serde::ser::SerializeMap;
        match self {
            Self::Conflict => serializer.serialize_str("conflict"),
            Self::IntegrityMismatch => serializer.serialize_str("integrity_mismatch"),
            Self::IntegrityMissing => serializer.serialize_str("integrity_missing"),
            Self::InvalidInput => serializer.serialize_str("invalid_input"),
            Self::NotFound => serializer.serialize_str("not_found"),
            Self::Unauthorized => serializer.serialize_str("unauthorized"),
            Self::UploadExpired => serializer.serialize_str("upload_expired"),
            Self::UploadInterrupted => serializer.serialize_str("upload_interrupted"),
            Self::UploadMissing => serializer.serialize_str("upload_missing"),
            Self::UploadRejected => serializer.serialize_str("upload_rejected"),
            Self::Unknown(value) => {
                let mut map = serializer.serialize_map(Some(1 + usize::from(value.payload.is_some()) + value.extra.len()))?;
                map.serialize_entry("code", &value.code)?;
                if let Some(payload) = &value.payload {
                    map.serialize_entry("payload", payload)?;
                }
                for (key, extra) in &value.extra {
                    map.serialize_entry(key, extra)?;
                }
                map.end()
            },
        }
    }
}

impl<'de> serde::Deserialize<'de> for ReleaseClaimError {
    fn deserialize<D>(deserializer: D) -> Result<Self, D::Error>
    where
        D: serde::Deserializer<'de>,
    {
        let value = <serde_json::Value as serde::Deserialize>::deserialize(deserializer)?;
        match value {
            serde_json::Value::String(code) => match code.as_str() {
                "conflict" => Ok(Self::Conflict),
                "integrity_mismatch" => Ok(Self::IntegrityMismatch),
                "integrity_missing" => Ok(Self::IntegrityMissing),
                "invalid_input" => Ok(Self::InvalidInput),
                "not_found" => Ok(Self::NotFound),
                "unauthorized" => Ok(Self::Unauthorized),
                "upload_expired" => Ok(Self::UploadExpired),
                "upload_interrupted" => Ok(Self::UploadInterrupted),
                "upload_missing" => Ok(Self::UploadMissing),
                "upload_rejected" => Ok(Self::UploadRejected),
                _ => Ok(Self::Unknown(UnknownDomainError { code, payload: None, extra: std::collections::BTreeMap::new() })),
            },
            serde_json::Value::Object(mut object) => {
                let Some(code) = object.remove("code").and_then(|value| value.as_str().map(ToOwned::to_owned)) else {
                    return Err(serde::de::Error::custom("Domain Error object is missing a string code"));
                };
                let payload = object.remove("payload");
                let extra = object.into_iter().collect::<std::collections::BTreeMap<_, _>>();
                Ok(Self::Unknown(UnknownDomainError { code, payload, extra }))
            }
            other => Err(serde::de::Error::custom(format!("Domain Error must be a string or object, got {other}"))),
        }
    }
}

impl serde::Serialize for ReserveError {
    fn serialize<S>(&self, serializer: S) -> Result<S::Ok, S::Error>
    where
        S: serde::Serializer,
    {
        use serde::ser::SerializeMap;
        match self {
            Self::Conflict => serializer.serialize_str("conflict"),
            Self::IntegrityMismatch => serializer.serialize_str("integrity_mismatch"),
            Self::IntegrityMissing => serializer.serialize_str("integrity_missing"),
            Self::InvalidInput => serializer.serialize_str("invalid_input"),
            Self::NotFound => serializer.serialize_str("not_found"),
            Self::Unauthorized => serializer.serialize_str("unauthorized"),
            Self::UploadExpired => serializer.serialize_str("upload_expired"),
            Self::UploadInterrupted => serializer.serialize_str("upload_interrupted"),
            Self::UploadMissing => serializer.serialize_str("upload_missing"),
            Self::UploadRejected => serializer.serialize_str("upload_rejected"),
            Self::Unknown(value) => {
                let mut map = serializer.serialize_map(Some(1 + usize::from(value.payload.is_some()) + value.extra.len()))?;
                map.serialize_entry("code", &value.code)?;
                if let Some(payload) = &value.payload {
                    map.serialize_entry("payload", payload)?;
                }
                for (key, extra) in &value.extra {
                    map.serialize_entry(key, extra)?;
                }
                map.end()
            },
        }
    }
}

impl<'de> serde::Deserialize<'de> for ReserveError {
    fn deserialize<D>(deserializer: D) -> Result<Self, D::Error>
    where
        D: serde::Deserializer<'de>,
    {
        let value = <serde_json::Value as serde::Deserialize>::deserialize(deserializer)?;
        match value {
            serde_json::Value::String(code) => match code.as_str() {
                "conflict" => Ok(Self::Conflict),
                "integrity_mismatch" => Ok(Self::IntegrityMismatch),
                "integrity_missing" => Ok(Self::IntegrityMissing),
                "invalid_input" => Ok(Self::InvalidInput),
                "not_found" => Ok(Self::NotFound),
                "unauthorized" => Ok(Self::Unauthorized),
                "upload_expired" => Ok(Self::UploadExpired),
                "upload_interrupted" => Ok(Self::UploadInterrupted),
                "upload_missing" => Ok(Self::UploadMissing),
                "upload_rejected" => Ok(Self::UploadRejected),
                _ => Ok(Self::Unknown(UnknownDomainError { code, payload: None, extra: std::collections::BTreeMap::new() })),
            },
            serde_json::Value::Object(mut object) => {
                let Some(code) = object.remove("code").and_then(|value| value.as_str().map(ToOwned::to_owned)) else {
                    return Err(serde::de::Error::custom("Domain Error object is missing a string code"));
                };
                let payload = object.remove("payload");
                let extra = object.into_iter().collect::<std::collections::BTreeMap<_, _>>();
                Ok(Self::Unknown(UnknownDomainError { code, payload, extra }))
            }
            other => Err(serde::de::Error::custom(format!("Domain Error must be a string or object, got {other}"))),
        }
    }
}

impl serde::Serialize for SweepError {
    fn serialize<S>(&self, serializer: S) -> Result<S::Ok, S::Error>
    where
        S: serde::Serializer,
    {
        use serde::ser::SerializeMap;
        match self {
            Self::Conflict => serializer.serialize_str("conflict"),
            Self::IntegrityMismatch => serializer.serialize_str("integrity_mismatch"),
            Self::IntegrityMissing => serializer.serialize_str("integrity_missing"),
            Self::InvalidInput => serializer.serialize_str("invalid_input"),
            Self::NotFound => serializer.serialize_str("not_found"),
            Self::Unauthorized => serializer.serialize_str("unauthorized"),
            Self::UploadExpired => serializer.serialize_str("upload_expired"),
            Self::UploadInterrupted => serializer.serialize_str("upload_interrupted"),
            Self::UploadMissing => serializer.serialize_str("upload_missing"),
            Self::UploadRejected => serializer.serialize_str("upload_rejected"),
            Self::Unknown(value) => {
                let mut map = serializer.serialize_map(Some(1 + usize::from(value.payload.is_some()) + value.extra.len()))?;
                map.serialize_entry("code", &value.code)?;
                if let Some(payload) = &value.payload {
                    map.serialize_entry("payload", payload)?;
                }
                for (key, extra) in &value.extra {
                    map.serialize_entry(key, extra)?;
                }
                map.end()
            },
        }
    }
}

impl<'de> serde::Deserialize<'de> for SweepError {
    fn deserialize<D>(deserializer: D) -> Result<Self, D::Error>
    where
        D: serde::Deserializer<'de>,
    {
        let value = <serde_json::Value as serde::Deserialize>::deserialize(deserializer)?;
        match value {
            serde_json::Value::String(code) => match code.as_str() {
                "conflict" => Ok(Self::Conflict),
                "integrity_mismatch" => Ok(Self::IntegrityMismatch),
                "integrity_missing" => Ok(Self::IntegrityMissing),
                "invalid_input" => Ok(Self::InvalidInput),
                "not_found" => Ok(Self::NotFound),
                "unauthorized" => Ok(Self::Unauthorized),
                "upload_expired" => Ok(Self::UploadExpired),
                "upload_interrupted" => Ok(Self::UploadInterrupted),
                "upload_missing" => Ok(Self::UploadMissing),
                "upload_rejected" => Ok(Self::UploadRejected),
                _ => Ok(Self::Unknown(UnknownDomainError { code, payload: None, extra: std::collections::BTreeMap::new() })),
            },
            serde_json::Value::Object(mut object) => {
                let Some(code) = object.remove("code").and_then(|value| value.as_str().map(ToOwned::to_owned)) else {
                    return Err(serde::de::Error::custom("Domain Error object is missing a string code"));
                };
                let payload = object.remove("payload");
                let extra = object.into_iter().collect::<std::collections::BTreeMap<_, _>>();
                Ok(Self::Unknown(UnknownDomainError { code, payload, extra }))
            }
            other => Err(serde::de::Error::custom(format!("Domain Error must be a string or object, got {other}"))),
        }
    }
}

impl serde::Serialize for UploadError {
    fn serialize<S>(&self, serializer: S) -> Result<S::Ok, S::Error>
    where
        S: serde::Serializer,
    {
        use serde::ser::SerializeMap;
        match self {
            Self::Conflict => serializer.serialize_str("conflict"),
            Self::IntegrityMismatch => serializer.serialize_str("integrity_mismatch"),
            Self::IntegrityMissing => serializer.serialize_str("integrity_missing"),
            Self::InvalidInput => serializer.serialize_str("invalid_input"),
            Self::NotFound => serializer.serialize_str("not_found"),
            Self::Unauthorized => serializer.serialize_str("unauthorized"),
            Self::UploadExpired => serializer.serialize_str("upload_expired"),
            Self::UploadInterrupted => serializer.serialize_str("upload_interrupted"),
            Self::UploadMissing => serializer.serialize_str("upload_missing"),
            Self::UploadRejected => serializer.serialize_str("upload_rejected"),
            Self::Unknown(value) => {
                let mut map = serializer.serialize_map(Some(1 + usize::from(value.payload.is_some()) + value.extra.len()))?;
                map.serialize_entry("code", &value.code)?;
                if let Some(payload) = &value.payload {
                    map.serialize_entry("payload", payload)?;
                }
                for (key, extra) in &value.extra {
                    map.serialize_entry(key, extra)?;
                }
                map.end()
            },
        }
    }
}

impl<'de> serde::Deserialize<'de> for UploadError {
    fn deserialize<D>(deserializer: D) -> Result<Self, D::Error>
    where
        D: serde::Deserializer<'de>,
    {
        let value = <serde_json::Value as serde::Deserialize>::deserialize(deserializer)?;
        match value {
            serde_json::Value::String(code) => match code.as_str() {
                "conflict" => Ok(Self::Conflict),
                "integrity_mismatch" => Ok(Self::IntegrityMismatch),
                "integrity_missing" => Ok(Self::IntegrityMissing),
                "invalid_input" => Ok(Self::InvalidInput),
                "not_found" => Ok(Self::NotFound),
                "unauthorized" => Ok(Self::Unauthorized),
                "upload_expired" => Ok(Self::UploadExpired),
                "upload_interrupted" => Ok(Self::UploadInterrupted),
                "upload_missing" => Ok(Self::UploadMissing),
                "upload_rejected" => Ok(Self::UploadRejected),
                _ => Ok(Self::Unknown(UnknownDomainError { code, payload: None, extra: std::collections::BTreeMap::new() })),
            },
            serde_json::Value::Object(mut object) => {
                let Some(code) = object.remove("code").and_then(|value| value.as_str().map(ToOwned::to_owned)) else {
                    return Err(serde::de::Error::custom("Domain Error object is missing a string code"));
                };
                let payload = object.remove("payload");
                let extra = object.into_iter().collect::<std::collections::BTreeMap<_, _>>();
                Ok(Self::Unknown(UnknownDomainError { code, payload, extra }))
            }
            other => Err(serde::de::Error::custom(format!("Domain Error must be a string or object, got {other}"))),
        }
    }
}

pub fn encode_claim_request(value: &ClaimRequest) -> Result<String, serde_json::Error> { encode_portable_json(value) }
pub fn decode_claim_request(wire: &str) -> Result<ClaimRequest, serde_json::Error> { decode_portable_json(wire) }
pub fn encode_claim_response(value: &ClaimResponse) -> Result<String, serde_json::Error> { encode_portable_json(value) }
pub fn decode_claim_response(wire: &str) -> Result<ClaimResponse, serde_json::Error> { decode_portable_json(wire) }
pub fn encode_claim_error(value: &ClaimError) -> Result<String, serde_json::Error> { encode_portable_json(value) }
pub fn decode_claim_error(wire: &str) -> Result<ClaimError, serde_json::Error> { decode_portable_json(wire) }

pub fn encode_describe_request(value: &DescribeRequest) -> Result<String, serde_json::Error> { encode_portable_json(value) }
pub fn decode_describe_request(wire: &str) -> Result<DescribeRequest, serde_json::Error> { decode_portable_json(wire) }
pub fn encode_describe_response(value: &DescribeResponse) -> Result<String, serde_json::Error> { encode_portable_json(value) }
pub fn decode_describe_response(wire: &str) -> Result<DescribeResponse, serde_json::Error> { decode_portable_json(wire) }
pub fn encode_describe_error(value: &DescribeError) -> Result<String, serde_json::Error> { encode_portable_json(value) }
pub fn decode_describe_error(wire: &str) -> Result<DescribeError, serde_json::Error> { decode_portable_json(wire) }

pub fn encode_download_request(value: &DownloadRequest) -> Result<String, serde_json::Error> { encode_portable_json(value) }
pub fn decode_download_request(wire: &str) -> Result<DownloadRequest, serde_json::Error> { decode_portable_json(wire) }
pub fn encode_download_response(value: &DownloadFrame) -> Result<String, serde_json::Error> { encode_portable_json(value) }
pub fn decode_download_response(wire: &str) -> Result<DownloadFrame, serde_json::Error> { decode_portable_json(wire) }
pub fn encode_download_error(value: &DownloadError) -> Result<String, serde_json::Error> { encode_portable_json(value) }
pub fn decode_download_error(wire: &str) -> Result<DownloadError, serde_json::Error> { decode_portable_json(wire) }

pub fn encode_release_claim_request(value: &ReleaseClaimRequest) -> Result<String, serde_json::Error> { encode_portable_json(value) }
pub fn decode_release_claim_request(wire: &str) -> Result<ReleaseClaimRequest, serde_json::Error> { decode_portable_json(wire) }
pub fn encode_release_claim_response(value: &ReleaseClaimResponse) -> Result<String, serde_json::Error> { encode_portable_json(value) }
pub fn decode_release_claim_response(wire: &str) -> Result<ReleaseClaimResponse, serde_json::Error> { decode_portable_json(wire) }
pub fn encode_release_claim_error(value: &ReleaseClaimError) -> Result<String, serde_json::Error> { encode_portable_json(value) }
pub fn decode_release_claim_error(wire: &str) -> Result<ReleaseClaimError, serde_json::Error> { decode_portable_json(wire) }

pub fn encode_reserve_request(value: &ReserveRequest) -> Result<String, serde_json::Error> { encode_portable_json(value) }
pub fn decode_reserve_request(wire: &str) -> Result<ReserveRequest, serde_json::Error> { decode_portable_json(wire) }
pub fn encode_reserve_response(value: &ReserveResponse) -> Result<String, serde_json::Error> { encode_portable_json(value) }
pub fn decode_reserve_response(wire: &str) -> Result<ReserveResponse, serde_json::Error> { decode_portable_json(wire) }
pub fn encode_reserve_error(value: &ReserveError) -> Result<String, serde_json::Error> { encode_portable_json(value) }
pub fn decode_reserve_error(wire: &str) -> Result<ReserveError, serde_json::Error> { decode_portable_json(wire) }

pub fn encode_sweep_request(value: &SweepRequest) -> Result<String, serde_json::Error> { encode_portable_json(value) }
pub fn decode_sweep_request(wire: &str) -> Result<SweepRequest, serde_json::Error> { decode_portable_json(wire) }
pub fn encode_sweep_response(value: &SweepResponse) -> Result<String, serde_json::Error> { encode_portable_json(value) }
pub fn decode_sweep_response(wire: &str) -> Result<SweepResponse, serde_json::Error> { decode_portable_json(wire) }
pub fn encode_sweep_error(value: &SweepError) -> Result<String, serde_json::Error> { encode_portable_json(value) }
pub fn decode_sweep_error(wire: &str) -> Result<SweepError, serde_json::Error> { decode_portable_json(wire) }

pub fn encode_upload_request(value: &UploadRequest) -> Result<String, serde_json::Error> { encode_portable_json(value) }
pub fn decode_upload_request(wire: &str) -> Result<UploadRequest, serde_json::Error> { decode_portable_json(wire) }
pub fn encode_upload_response(value: &UploadFrame) -> Result<String, serde_json::Error> { encode_portable_json(value) }
pub fn decode_upload_response(wire: &str) -> Result<UploadFrame, serde_json::Error> { decode_portable_json(wire) }
pub fn encode_upload_error(value: &UploadError) -> Result<String, serde_json::Error> { encode_portable_json(value) }
pub fn decode_upload_error(wire: &str) -> Result<UploadError, serde_json::Error> { decode_portable_json(wire) }

#[doc(hidden)]
pub trait __LensoIntoContentVaultClaimResult {
    fn __lenso_into_result(self) -> Result<Result<ClaimResponse, ClaimError>, RuntimeFailure>;
}
impl __LensoIntoContentVaultClaimResult for Result<ClaimResponse, ClaimError> {
    fn __lenso_into_result(self) -> Result<Result<ClaimResponse, ClaimError>, RuntimeFailure> { Ok(self) }
}
impl __LensoIntoContentVaultClaimResult for Result<Result<ClaimResponse, ClaimError>, RuntimeFailure> {
    fn __lenso_into_result(self) -> Result<Result<ClaimResponse, ClaimError>, RuntimeFailure> { self }
}
impl __LensoIntoContentVaultClaimResult for Result<ClaimResponse, lenso_plugin_authoring::PluginError<ClaimError, RuntimeFailure>> {
    fn __lenso_into_result(self) -> Result<Result<ClaimResponse, ClaimError>, RuntimeFailure> {
        match self {
            Ok(value) => Ok(Ok(value)),
            Err(lenso_plugin_authoring::PluginError::Domain(error)) => Ok(Err(error)),
            Err(lenso_plugin_authoring::PluginError::Runtime(error)) => Err(error),
        }
    }
}
impl __LensoIntoContentVaultClaimResult for Result<ClaimResponse, ContentVaultClaimInvocationError> {
    fn __lenso_into_result(self) -> Result<Result<ClaimResponse, ClaimError>, RuntimeFailure> {
        match self {
            Ok(value) => Ok(Ok(value)),
            Err(ContentVaultClaimInvocationError::Domain(error)) => Ok(Err(error)),
            Err(ContentVaultClaimInvocationError::Runtime(error)) => Err(error),
        }
    }
}

#[doc(hidden)]
pub trait __LensoIntoContentVaultDescribeResult {
    fn __lenso_into_result(self) -> Result<Result<DescribeResponse, DescribeError>, RuntimeFailure>;
}
impl __LensoIntoContentVaultDescribeResult for Result<DescribeResponse, DescribeError> {
    fn __lenso_into_result(self) -> Result<Result<DescribeResponse, DescribeError>, RuntimeFailure> { Ok(self) }
}
impl __LensoIntoContentVaultDescribeResult for Result<Result<DescribeResponse, DescribeError>, RuntimeFailure> {
    fn __lenso_into_result(self) -> Result<Result<DescribeResponse, DescribeError>, RuntimeFailure> { self }
}
impl __LensoIntoContentVaultDescribeResult for Result<DescribeResponse, lenso_plugin_authoring::PluginError<DescribeError, RuntimeFailure>> {
    fn __lenso_into_result(self) -> Result<Result<DescribeResponse, DescribeError>, RuntimeFailure> {
        match self {
            Ok(value) => Ok(Ok(value)),
            Err(lenso_plugin_authoring::PluginError::Domain(error)) => Ok(Err(error)),
            Err(lenso_plugin_authoring::PluginError::Runtime(error)) => Err(error),
        }
    }
}
impl __LensoIntoContentVaultDescribeResult for Result<DescribeResponse, ContentVaultDescribeInvocationError> {
    fn __lenso_into_result(self) -> Result<Result<DescribeResponse, DescribeError>, RuntimeFailure> {
        match self {
            Ok(value) => Ok(Ok(value)),
            Err(ContentVaultDescribeInvocationError::Domain(error)) => Ok(Err(error)),
            Err(ContentVaultDescribeInvocationError::Runtime(error)) => Err(error),
        }
    }
}

#[doc(hidden)]
pub trait __LensoIntoContentVaultDownloadStreamResult {
    fn __lenso_into_result(self) -> Result<Box<dyn NativeStreamSession>, ContentVaultDownloadInvocationError>;
}
impl<S> __LensoIntoContentVaultDownloadStreamResult for Result<S, DownloadError>
where
    S: NativeStreamSession + 'static,
{
    fn __lenso_into_result(self) -> Result<Box<dyn NativeStreamSession>, ContentVaultDownloadInvocationError> {
        self.map(|stream| Box::new(stream) as Box<dyn NativeStreamSession>)
            .map_err(ContentVaultDownloadInvocationError::Domain)
    }
}
impl<S> __LensoIntoContentVaultDownloadStreamResult for Result<S, lenso_plugin_authoring::PluginError<DownloadError, RuntimeFailure>>
where
    S: NativeStreamSession + 'static,
{
    fn __lenso_into_result(self) -> Result<Box<dyn NativeStreamSession>, ContentVaultDownloadInvocationError> {
        match self {
            Ok(stream) => Ok(Box::new(stream) as Box<dyn NativeStreamSession>),
            Err(lenso_plugin_authoring::PluginError::Domain(error)) => Err(ContentVaultDownloadInvocationError::Domain(error)),
            Err(lenso_plugin_authoring::PluginError::Runtime(error)) => Err(ContentVaultDownloadInvocationError::Runtime(error)),
        }
    }
}
impl<S> __LensoIntoContentVaultDownloadStreamResult for Result<S, ContentVaultDownloadInvocationError>
where
    S: NativeStreamSession + 'static,
{
    fn __lenso_into_result(self) -> Result<Box<dyn NativeStreamSession>, ContentVaultDownloadInvocationError> {
        self.map(|stream| Box::new(stream) as Box<dyn NativeStreamSession>)
    }
}

#[doc(hidden)]
pub trait __LensoIntoContentVaultReleaseClaimResult {
    fn __lenso_into_result(self) -> Result<Result<ReleaseClaimResponse, ReleaseClaimError>, RuntimeFailure>;
}
impl __LensoIntoContentVaultReleaseClaimResult for Result<ReleaseClaimResponse, ReleaseClaimError> {
    fn __lenso_into_result(self) -> Result<Result<ReleaseClaimResponse, ReleaseClaimError>, RuntimeFailure> { Ok(self) }
}
impl __LensoIntoContentVaultReleaseClaimResult for Result<Result<ReleaseClaimResponse, ReleaseClaimError>, RuntimeFailure> {
    fn __lenso_into_result(self) -> Result<Result<ReleaseClaimResponse, ReleaseClaimError>, RuntimeFailure> { self }
}
impl __LensoIntoContentVaultReleaseClaimResult for Result<ReleaseClaimResponse, lenso_plugin_authoring::PluginError<ReleaseClaimError, RuntimeFailure>> {
    fn __lenso_into_result(self) -> Result<Result<ReleaseClaimResponse, ReleaseClaimError>, RuntimeFailure> {
        match self {
            Ok(value) => Ok(Ok(value)),
            Err(lenso_plugin_authoring::PluginError::Domain(error)) => Ok(Err(error)),
            Err(lenso_plugin_authoring::PluginError::Runtime(error)) => Err(error),
        }
    }
}
impl __LensoIntoContentVaultReleaseClaimResult for Result<ReleaseClaimResponse, ContentVaultReleaseClaimInvocationError> {
    fn __lenso_into_result(self) -> Result<Result<ReleaseClaimResponse, ReleaseClaimError>, RuntimeFailure> {
        match self {
            Ok(value) => Ok(Ok(value)),
            Err(ContentVaultReleaseClaimInvocationError::Domain(error)) => Ok(Err(error)),
            Err(ContentVaultReleaseClaimInvocationError::Runtime(error)) => Err(error),
        }
    }
}

#[doc(hidden)]
pub trait __LensoIntoContentVaultReserveResult {
    fn __lenso_into_result(self) -> Result<Result<ReserveResponse, ReserveError>, RuntimeFailure>;
}
impl __LensoIntoContentVaultReserveResult for Result<ReserveResponse, ReserveError> {
    fn __lenso_into_result(self) -> Result<Result<ReserveResponse, ReserveError>, RuntimeFailure> { Ok(self) }
}
impl __LensoIntoContentVaultReserveResult for Result<Result<ReserveResponse, ReserveError>, RuntimeFailure> {
    fn __lenso_into_result(self) -> Result<Result<ReserveResponse, ReserveError>, RuntimeFailure> { self }
}
impl __LensoIntoContentVaultReserveResult for Result<ReserveResponse, lenso_plugin_authoring::PluginError<ReserveError, RuntimeFailure>> {
    fn __lenso_into_result(self) -> Result<Result<ReserveResponse, ReserveError>, RuntimeFailure> {
        match self {
            Ok(value) => Ok(Ok(value)),
            Err(lenso_plugin_authoring::PluginError::Domain(error)) => Ok(Err(error)),
            Err(lenso_plugin_authoring::PluginError::Runtime(error)) => Err(error),
        }
    }
}
impl __LensoIntoContentVaultReserveResult for Result<ReserveResponse, ContentVaultReserveInvocationError> {
    fn __lenso_into_result(self) -> Result<Result<ReserveResponse, ReserveError>, RuntimeFailure> {
        match self {
            Ok(value) => Ok(Ok(value)),
            Err(ContentVaultReserveInvocationError::Domain(error)) => Ok(Err(error)),
            Err(ContentVaultReserveInvocationError::Runtime(error)) => Err(error),
        }
    }
}

#[doc(hidden)]
pub trait __LensoIntoContentVaultSweepResult {
    fn __lenso_into_result(self) -> Result<Result<SweepResponse, SweepError>, RuntimeFailure>;
}
impl __LensoIntoContentVaultSweepResult for Result<SweepResponse, SweepError> {
    fn __lenso_into_result(self) -> Result<Result<SweepResponse, SweepError>, RuntimeFailure> { Ok(self) }
}
impl __LensoIntoContentVaultSweepResult for Result<Result<SweepResponse, SweepError>, RuntimeFailure> {
    fn __lenso_into_result(self) -> Result<Result<SweepResponse, SweepError>, RuntimeFailure> { self }
}
impl __LensoIntoContentVaultSweepResult for Result<SweepResponse, lenso_plugin_authoring::PluginError<SweepError, RuntimeFailure>> {
    fn __lenso_into_result(self) -> Result<Result<SweepResponse, SweepError>, RuntimeFailure> {
        match self {
            Ok(value) => Ok(Ok(value)),
            Err(lenso_plugin_authoring::PluginError::Domain(error)) => Ok(Err(error)),
            Err(lenso_plugin_authoring::PluginError::Runtime(error)) => Err(error),
        }
    }
}
impl __LensoIntoContentVaultSweepResult for Result<SweepResponse, ContentVaultSweepInvocationError> {
    fn __lenso_into_result(self) -> Result<Result<SweepResponse, SweepError>, RuntimeFailure> {
        match self {
            Ok(value) => Ok(Ok(value)),
            Err(ContentVaultSweepInvocationError::Domain(error)) => Ok(Err(error)),
            Err(ContentVaultSweepInvocationError::Runtime(error)) => Err(error),
        }
    }
}

#[doc(hidden)]
pub trait __LensoIntoContentVaultUploadStreamResult {
    fn __lenso_into_result(self) -> Result<Box<dyn NativeStreamSession>, ContentVaultUploadInvocationError>;
}
impl<S> __LensoIntoContentVaultUploadStreamResult for Result<S, UploadError>
where
    S: NativeStreamSession + 'static,
{
    fn __lenso_into_result(self) -> Result<Box<dyn NativeStreamSession>, ContentVaultUploadInvocationError> {
        self.map(|stream| Box::new(stream) as Box<dyn NativeStreamSession>)
            .map_err(ContentVaultUploadInvocationError::Domain)
    }
}
impl<S> __LensoIntoContentVaultUploadStreamResult for Result<S, lenso_plugin_authoring::PluginError<UploadError, RuntimeFailure>>
where
    S: NativeStreamSession + 'static,
{
    fn __lenso_into_result(self) -> Result<Box<dyn NativeStreamSession>, ContentVaultUploadInvocationError> {
        match self {
            Ok(stream) => Ok(Box::new(stream) as Box<dyn NativeStreamSession>),
            Err(lenso_plugin_authoring::PluginError::Domain(error)) => Err(ContentVaultUploadInvocationError::Domain(error)),
            Err(lenso_plugin_authoring::PluginError::Runtime(error)) => Err(ContentVaultUploadInvocationError::Runtime(error)),
        }
    }
}
impl<S> __LensoIntoContentVaultUploadStreamResult for Result<S, ContentVaultUploadInvocationError>
where
    S: NativeStreamSession + 'static,
{
    fn __lenso_into_result(self) -> Result<Box<dyn NativeStreamSession>, ContentVaultUploadInvocationError> {
        self.map(|stream| Box::new(stream) as Box<dyn NativeStreamSession>)
    }
}

pub trait ContentVaultProvider: fmt::Debug + 'static {
    fn claim(&self, context: InvocationContext, request: ClaimRequest) -> NativeRequestFuture<ContentVaultClaim>;
    fn describe(&self, context: InvocationContext, request: DescribeRequest) -> NativeRequestFuture<ContentVaultDescribe>;
    fn download(&self, context: InvocationContext, request: DownloadRequest) -> LocalBoxFuture<'static, Result<Box<dyn NativeStreamSession>, ContentVaultDownloadInvocationError>>;
    fn release_claim(&self, context: InvocationContext, request: ReleaseClaimRequest) -> NativeRequestFuture<ContentVaultReleaseClaim>;
    fn reserve(&self, context: InvocationContext, request: ReserveRequest) -> NativeRequestFuture<ContentVaultReserve>;
    fn sweep(&self, context: InvocationContext, request: SweepRequest) -> NativeRequestFuture<ContentVaultSweep>;
    fn upload(&self, context: InvocationContext, request: UploadRequest) -> LocalBoxFuture<'static, Result<Box<dyn NativeStreamSession>, ContentVaultUploadInvocationError>>;
}

#[doc(hidden)]
#[macro_export]
macro_rules! __lenso_native_lower_content_vault {
    ($plugin:ty, $support:path) => {
        use $support as __LensoNativeSupportContentVault;
        impl $crate::ContentVaultProvider for $plugin {
        fn claim(&self, context: __LensoNativeSupportContentVault::InvocationContext, request: $crate::ClaimRequest) -> __LensoNativeSupportContentVault::NativeRequestFuture<$crate::ContentVaultClaim> {
            let plugin = self.clone();
            ::std::boxed::Box::pin(async move {
                let result = <$plugin>::claim(&plugin, context, request).await;
                $crate::__LensoIntoContentVaultClaimResult::__lenso_into_result(result)
            })
        }
        fn describe(&self, context: __LensoNativeSupportContentVault::InvocationContext, request: $crate::DescribeRequest) -> __LensoNativeSupportContentVault::NativeRequestFuture<$crate::ContentVaultDescribe> {
            let plugin = self.clone();
            ::std::boxed::Box::pin(async move {
                let result = <$plugin>::describe(&plugin, context, request).await;
                $crate::__LensoIntoContentVaultDescribeResult::__lenso_into_result(result)
            })
        }
        fn download(&self, context: __LensoNativeSupportContentVault::InvocationContext, request: $crate::DownloadRequest) -> __LensoNativeSupportContentVault::LocalBoxFuture<'static, Result<Box<dyn __LensoNativeSupportContentVault::NativeStreamSession>, $crate::ContentVaultDownloadInvocationError>> {
            let plugin = self.clone();
            ::std::boxed::Box::pin(async move {
                let result = <$plugin>::download(&plugin, context, request).await;
                $crate::__LensoIntoContentVaultDownloadStreamResult::__lenso_into_result(result)
            })
        }
        fn release_claim(&self, context: __LensoNativeSupportContentVault::InvocationContext, request: $crate::ReleaseClaimRequest) -> __LensoNativeSupportContentVault::NativeRequestFuture<$crate::ContentVaultReleaseClaim> {
            let plugin = self.clone();
            ::std::boxed::Box::pin(async move {
                let result = <$plugin>::release_claim(&plugin, context, request).await;
                $crate::__LensoIntoContentVaultReleaseClaimResult::__lenso_into_result(result)
            })
        }
        fn reserve(&self, context: __LensoNativeSupportContentVault::InvocationContext, request: $crate::ReserveRequest) -> __LensoNativeSupportContentVault::NativeRequestFuture<$crate::ContentVaultReserve> {
            let plugin = self.clone();
            ::std::boxed::Box::pin(async move {
                let result = <$plugin>::reserve(&plugin, context, request).await;
                $crate::__LensoIntoContentVaultReserveResult::__lenso_into_result(result)
            })
        }
        fn sweep(&self, context: __LensoNativeSupportContentVault::InvocationContext, request: $crate::SweepRequest) -> __LensoNativeSupportContentVault::NativeRequestFuture<$crate::ContentVaultSweep> {
            let plugin = self.clone();
            ::std::boxed::Box::pin(async move {
                let result = <$plugin>::sweep(&plugin, context, request).await;
                $crate::__LensoIntoContentVaultSweepResult::__lenso_into_result(result)
            })
        }
        fn upload(&self, context: __LensoNativeSupportContentVault::InvocationContext, request: $crate::UploadRequest) -> __LensoNativeSupportContentVault::LocalBoxFuture<'static, Result<Box<dyn __LensoNativeSupportContentVault::NativeStreamSession>, $crate::ContentVaultUploadInvocationError>> {
            let plugin = self.clone();
            ::std::boxed::Box::pin(async move {
                let result = <$plugin>::upload(&plugin, context, request).await;
                $crate::__LensoIntoContentVaultUploadStreamResult::__lenso_into_result(result)
            })
        }
        }
    };
}

#[derive(Debug)]
struct ContentVaultRequestEndpoint { provider: Rc<dyn ContentVaultProvider> }

#[derive(Debug)]
pub struct ContentVaultEndpoint<P: ContentVaultProvider> { provider: Rc<P>, request_endpoint: ContentVaultRequestEndpoint }
impl<P: ContentVaultProvider> ContentVaultEndpoint<P> {
    pub fn new(provider: P) -> Self {
        let provider = Rc::new(provider);
        let request_provider: Rc<dyn ContentVaultProvider> = provider.clone();
        Self { provider, request_endpoint: ContentVaultRequestEndpoint { provider: request_provider } }
    }
}

impl<P: ContentVaultProvider> NativeRequestEndpoint for ContentVaultEndpoint<P> {
    fn capability_id(&self) -> &'static str { CAPABILITY_ID }
    fn descriptor_version(&self) -> &'static str { DESCRIPTOR_VERSION }
    fn operations(&self) -> &'static [&'static str] { &[
        CLAIM_OPERATION,
        DESCRIBE_OPERATION,
        RELEASE_CLAIM_OPERATION,
        RESERVE_OPERATION,
        SWEEP_OPERATION,
    ] }
    fn typed_endpoint(&self) -> Option<&dyn std::any::Any> { Some(&self.request_endpoint) }
    fn invoke(&self, operation: &str, request: Box<dyn std::any::Any>, context: InvocationContext) -> LocalBoxFuture<'static, Result<Result<Box<dyn std::any::Any>, Box<dyn std::any::Any>>, RuntimeFailure>> {
        match operation {
            CLAIM_OPERATION => {
                let Ok(request) = request.downcast::<ClaimRequest>() else {
                    return Box::pin(futures::future::ready(Err(RuntimeFailure::ProtocolViolation { capability: CAPABILITY_ID })));
                };
                let invocation = Rc::clone(&self.provider).claim(context, *request);
                Box::pin(async move {
                    invocation.await.map(|result| {
                        result
                            .map(|value| Box::new(value) as Box<dyn std::any::Any>)
                            .map_err(|error| Box::new(error) as Box<dyn std::any::Any>)
                    })
                })
            },
            DESCRIBE_OPERATION => {
                let Ok(request) = request.downcast::<DescribeRequest>() else {
                    return Box::pin(futures::future::ready(Err(RuntimeFailure::ProtocolViolation { capability: CAPABILITY_ID })));
                };
                let invocation = Rc::clone(&self.provider).describe(context, *request);
                Box::pin(async move {
                    invocation.await.map(|result| {
                        result
                            .map(|value| Box::new(value) as Box<dyn std::any::Any>)
                            .map_err(|error| Box::new(error) as Box<dyn std::any::Any>)
                    })
                })
            },
            RELEASE_CLAIM_OPERATION => {
                let Ok(request) = request.downcast::<ReleaseClaimRequest>() else {
                    return Box::pin(futures::future::ready(Err(RuntimeFailure::ProtocolViolation { capability: CAPABILITY_ID })));
                };
                let invocation = Rc::clone(&self.provider).release_claim(context, *request);
                Box::pin(async move {
                    invocation.await.map(|result| {
                        result
                            .map(|value| Box::new(value) as Box<dyn std::any::Any>)
                            .map_err(|error| Box::new(error) as Box<dyn std::any::Any>)
                    })
                })
            },
            RESERVE_OPERATION => {
                let Ok(request) = request.downcast::<ReserveRequest>() else {
                    return Box::pin(futures::future::ready(Err(RuntimeFailure::ProtocolViolation { capability: CAPABILITY_ID })));
                };
                let invocation = Rc::clone(&self.provider).reserve(context, *request);
                Box::pin(async move {
                    invocation.await.map(|result| {
                        result
                            .map(|value| Box::new(value) as Box<dyn std::any::Any>)
                            .map_err(|error| Box::new(error) as Box<dyn std::any::Any>)
                    })
                })
            },
            SWEEP_OPERATION => {
                let Ok(request) = request.downcast::<SweepRequest>() else {
                    return Box::pin(futures::future::ready(Err(RuntimeFailure::ProtocolViolation { capability: CAPABILITY_ID })));
                };
                let invocation = Rc::clone(&self.provider).sweep(context, *request);
                Box::pin(async move {
                    invocation.await.map(|result| {
                        result
                            .map(|value| Box::new(value) as Box<dyn std::any::Any>)
                            .map_err(|error| Box::new(error) as Box<dyn std::any::Any>)
                    })
                })
            }
            _ => Box::pin(futures::future::ready(Err(RuntimeFailure::UnknownOperation { capability: CAPABILITY_ID, operation: operation.to_owned() }))),
        }
    }
}

impl<P: ContentVaultProvider> NativeStreamEndpoint for ContentVaultEndpoint<P> {
    fn capability_id(&self) -> &'static str { CAPABILITY_ID }
    fn descriptor_version(&self) -> &'static str { DESCRIPTOR_VERSION }
    fn operations(&self) -> &'static [&'static str] { &[
        DOWNLOAD_OPERATION,
        UPLOAD_OPERATION,
    ] }
    fn open(&self, operation: &str, request: Box<dyn std::any::Any>, context: InvocationContext) -> LocalBoxFuture<'static, Result<Result<Box<dyn NativeStreamSession>, Box<dyn std::any::Any>>, RuntimeFailure>> {
        match operation {
            DOWNLOAD_OPERATION => {
                let Ok(request) = request.downcast::<DownloadRequest>() else {
                    return Box::pin(futures::future::ready(Err(RuntimeFailure::ProtocolViolation { capability: CAPABILITY_ID })));
                };
                let provider = Rc::clone(&self.provider);
                Box::pin(async move {
                    match provider.download(context, *request).await {
                        Ok(value) => Ok(Ok(value as Box<dyn NativeStreamSession>)),
                        Err(ContentVaultDownloadInvocationError::Domain(error)) => Ok(Err(Box::new(error) as Box<dyn std::any::Any>)),
                        Err(ContentVaultDownloadInvocationError::Runtime(error)) => Err(error),
                    }
                })
            },
            UPLOAD_OPERATION => {
                let Ok(request) = request.downcast::<UploadRequest>() else {
                    return Box::pin(futures::future::ready(Err(RuntimeFailure::ProtocolViolation { capability: CAPABILITY_ID })));
                };
                let provider = Rc::clone(&self.provider);
                Box::pin(async move {
                    match provider.upload(context, *request).await {
                        Ok(value) => Ok(Ok(value as Box<dyn NativeStreamSession>)),
                        Err(ContentVaultUploadInvocationError::Domain(error)) => Ok(Err(Box::new(error) as Box<dyn std::any::Any>)),
                        Err(ContentVaultUploadInvocationError::Runtime(error)) => Err(error),
                    }
                })
            }
            _ => Box::pin(futures::future::ready(Err(RuntimeFailure::UnknownOperation { capability: CAPABILITY_ID, operation: operation.to_owned() }))),
        }
    }
}

#[doc(hidden)]
#[macro_export]
macro_rules! __lenso_native_endpoints_content_vault {
    ($provider:expr, $support:path) => {{
        use $support as __LensoNativeSupport;
        let endpoint = ::std::rc::Rc::new($crate::ContentVaultEndpoint::new($provider));
        (
            vec![endpoint.clone() as ::std::rc::Rc<dyn __LensoNativeSupport::NativeRequestEndpoint>],
            vec![endpoint.clone() as ::std::rc::Rc<dyn __LensoNativeSupport::NativeStreamEndpoint>],
            vec![],
        )
    }};
}

#[doc(hidden)]
#[macro_export]
macro_rules! __lenso_native_provide_content_vault {
    ($provider:expr, $lifecycle:expr, $support:path) => {{
        use $support as __LensoNativeSupport;
        let (request_endpoints, stream_endpoints, event_endpoints) =
            $crate::__lenso_native_endpoints_content_vault!($provider, $support);
        __LensoNativeSupport::NativePluginInstance::with_all_endpoints(
            request_endpoints,
            stream_endpoints,
            event_endpoints,
            $lifecycle,
        )
    }};
}

#[derive(Debug)]
pub struct ContentVaultClient {
    claim: NativeRequestHandle<ContentVaultClaim>,
    describe: NativeRequestHandle<ContentVaultDescribe>,
    download: NativeStreamHandle<ContentVaultDownload>,
    release_claim: NativeRequestHandle<ContentVaultReleaseClaim>,
    reserve: NativeRequestHandle<ContentVaultReserve>,
    sweep: NativeRequestHandle<ContentVaultSweep>,
    upload: NativeStreamHandle<ContentVaultUpload>,
}
impl ContentVaultClient {
    pub fn from_dependencies(dependencies: &PluginDependencies) -> Result<Self, RuntimeFailure> {
        <Self as CapabilityClient>::from_dependencies(dependencies)
    }

    pub async fn claim(&self, request: ClaimRequest) -> Result<ClaimResponse, ContentVaultClaimInvocationError> {
        self.claim.invoke(CLAIM_OPERATION, request).await
            .map_err(ContentVaultClaimInvocationError::Runtime)?
            .map_err(ContentVaultClaimInvocationError::Domain)
    }

    pub async fn claim_with_context(&self, context: InvocationContext, request: ClaimRequest) -> Result<ClaimResponse, ContentVaultClaimInvocationError> {
        self.claim.invoke_with_context(CLAIM_OPERATION, context, request).await
            .map_err(ContentVaultClaimInvocationError::Runtime)?
            .map_err(ContentVaultClaimInvocationError::Domain)
    }

    pub async fn describe(&self, request: DescribeRequest) -> Result<DescribeResponse, ContentVaultDescribeInvocationError> {
        self.describe.invoke(DESCRIBE_OPERATION, request).await
            .map_err(ContentVaultDescribeInvocationError::Runtime)?
            .map_err(ContentVaultDescribeInvocationError::Domain)
    }

    pub async fn describe_with_context(&self, context: InvocationContext, request: DescribeRequest) -> Result<DescribeResponse, ContentVaultDescribeInvocationError> {
        self.describe.invoke_with_context(DESCRIBE_OPERATION, context, request).await
            .map_err(ContentVaultDescribeInvocationError::Runtime)?
            .map_err(ContentVaultDescribeInvocationError::Domain)
    }

    pub async fn download(&self, request: DownloadRequest) -> Result<NativeStream<ContentVaultDownload>, ContentVaultDownloadInvocationError> {
        self.download.open(DOWNLOAD_OPERATION, request).await
            .map_err(ContentVaultDownloadInvocationError::Runtime)?
            .map_err(ContentVaultDownloadInvocationError::Domain)
    }

    pub async fn download_with_context(&self, context: InvocationContext, request: DownloadRequest) -> Result<NativeStream<ContentVaultDownload>, ContentVaultDownloadInvocationError> {
        self.download.open_with_context(DOWNLOAD_OPERATION, context, request).await
            .map_err(ContentVaultDownloadInvocationError::Runtime)?
            .map_err(ContentVaultDownloadInvocationError::Domain)
    }

    pub async fn release_claim(&self, request: ReleaseClaimRequest) -> Result<ReleaseClaimResponse, ContentVaultReleaseClaimInvocationError> {
        self.release_claim.invoke(RELEASE_CLAIM_OPERATION, request).await
            .map_err(ContentVaultReleaseClaimInvocationError::Runtime)?
            .map_err(ContentVaultReleaseClaimInvocationError::Domain)
    }

    pub async fn release_claim_with_context(&self, context: InvocationContext, request: ReleaseClaimRequest) -> Result<ReleaseClaimResponse, ContentVaultReleaseClaimInvocationError> {
        self.release_claim.invoke_with_context(RELEASE_CLAIM_OPERATION, context, request).await
            .map_err(ContentVaultReleaseClaimInvocationError::Runtime)?
            .map_err(ContentVaultReleaseClaimInvocationError::Domain)
    }

    pub async fn reserve(&self, request: ReserveRequest) -> Result<ReserveResponse, ContentVaultReserveInvocationError> {
        self.reserve.invoke(RESERVE_OPERATION, request).await
            .map_err(ContentVaultReserveInvocationError::Runtime)?
            .map_err(ContentVaultReserveInvocationError::Domain)
    }

    pub async fn reserve_with_context(&self, context: InvocationContext, request: ReserveRequest) -> Result<ReserveResponse, ContentVaultReserveInvocationError> {
        self.reserve.invoke_with_context(RESERVE_OPERATION, context, request).await
            .map_err(ContentVaultReserveInvocationError::Runtime)?
            .map_err(ContentVaultReserveInvocationError::Domain)
    }

    pub async fn sweep(&self, request: SweepRequest) -> Result<SweepResponse, ContentVaultSweepInvocationError> {
        self.sweep.invoke(SWEEP_OPERATION, request).await
            .map_err(ContentVaultSweepInvocationError::Runtime)?
            .map_err(ContentVaultSweepInvocationError::Domain)
    }

    pub async fn sweep_with_context(&self, context: InvocationContext, request: SweepRequest) -> Result<SweepResponse, ContentVaultSweepInvocationError> {
        self.sweep.invoke_with_context(SWEEP_OPERATION, context, request).await
            .map_err(ContentVaultSweepInvocationError::Runtime)?
            .map_err(ContentVaultSweepInvocationError::Domain)
    }

    pub async fn upload(&self, request: UploadRequest) -> Result<NativeStream<ContentVaultUpload>, ContentVaultUploadInvocationError> {
        self.upload.open(UPLOAD_OPERATION, request).await
            .map_err(ContentVaultUploadInvocationError::Runtime)?
            .map_err(ContentVaultUploadInvocationError::Domain)
    }

    pub async fn upload_with_context(&self, context: InvocationContext, request: UploadRequest) -> Result<NativeStream<ContentVaultUpload>, ContentVaultUploadInvocationError> {
        self.upload.open_with_context(UPLOAD_OPERATION, context, request).await
            .map_err(ContentVaultUploadInvocationError::Runtime)?
            .map_err(ContentVaultUploadInvocationError::Domain)
    }
}

impl CapabilityClient for ContentVaultClient {
    type Dependencies = PluginDependencies;
    type Error = RuntimeFailure;

    const CAPABILITY_ID: &'static str = CAPABILITY_ID;
    const DESCRIPTOR_VERSION: &'static str = DESCRIPTOR_VERSION;

    fn from_dependencies(dependencies: &PluginDependencies) -> Result<Self, RuntimeFailure> {
        Ok(Self {
            claim: dependencies.one::<ContentVaultClaim>()?,
            describe: dependencies.one::<ContentVaultDescribe>()?,
            download: dependencies.one_stream::<ContentVaultDownload>()?,
            release_claim: dependencies.one::<ContentVaultReleaseClaim>()?,
            reserve: dependencies.one::<ContentVaultReserve>()?,
            sweep: dependencies.one::<ContentVaultSweep>()?,
            upload: dependencies.one_stream::<ContentVaultUpload>()?,
        })
    }

    fn already_connected() -> RuntimeFailure {
        RuntimeFailure::PluginFailure {
            detail: format!("Capability Port {CAPABILITY_ID} was connected more than once"),
        }
    }
}

impl CapabilityClientMany for ContentVaultClient {
    fn many_from_dependencies(
        dependencies: &PluginDependencies,
    ) -> Result<Vec<BoundCapabilityClient<Self>>, RuntimeFailure> {
        dependencies
            .bindings()
            .iter()
            .filter(|binding| binding.capability_id() == CAPABILITY_ID)
            .map(|binding| {
                Ok(BoundCapabilityClient::new(
                    binding.provider_instance(),
                    Self {
                    claim: binding.handle().ok_or(RuntimeFailure::Unavailable { capability: CAPABILITY_ID })?.typed::<ContentVaultClaim>()?,
                    describe: binding.handle().ok_or(RuntimeFailure::Unavailable { capability: CAPABILITY_ID })?.typed::<ContentVaultDescribe>()?,
                    download: binding.stream_handle().ok_or(RuntimeFailure::Unavailable { capability: CAPABILITY_ID })?.typed::<ContentVaultDownload>()?,
                    release_claim: binding.handle().ok_or(RuntimeFailure::Unavailable { capability: CAPABILITY_ID })?.typed::<ContentVaultReleaseClaim>()?,
                    reserve: binding.handle().ok_or(RuntimeFailure::Unavailable { capability: CAPABILITY_ID })?.typed::<ContentVaultReserve>()?,
                    sweep: binding.handle().ok_or(RuntimeFailure::Unavailable { capability: CAPABILITY_ID })?.typed::<ContentVaultSweep>()?,
                    upload: binding.stream_handle().ok_or(RuntimeFailure::Unavailable { capability: CAPABILITY_ID })?.typed::<ContentVaultUpload>()?,
                    },
                ))
            })
            .collect()
    }
}

#[derive(Clone, Debug, PartialEq)]
pub enum ContentVaultClaimInvocationError {
    Domain(ClaimError),
    Runtime(RuntimeFailure),
}
#[derive(Clone, Debug, PartialEq)]
pub enum ContentVaultDescribeInvocationError {
    Domain(DescribeError),
    Runtime(RuntimeFailure),
}
#[derive(Clone, Debug, PartialEq)]
pub enum ContentVaultDownloadInvocationError {
    Domain(DownloadError),
    Runtime(RuntimeFailure),
}
#[derive(Clone, Debug, PartialEq)]
pub enum ContentVaultReleaseClaimInvocationError {
    Domain(ReleaseClaimError),
    Runtime(RuntimeFailure),
}
#[derive(Clone, Debug, PartialEq)]
pub enum ContentVaultReserveInvocationError {
    Domain(ReserveError),
    Runtime(RuntimeFailure),
}
#[derive(Clone, Debug, PartialEq)]
pub enum ContentVaultSweepInvocationError {
    Domain(SweepError),
    Runtime(RuntimeFailure),
}
#[derive(Clone, Debug, PartialEq)]
pub enum ContentVaultUploadInvocationError {
    Domain(UploadError),
    Runtime(RuntimeFailure),
}
